speller:
  algebra:
    声调:
      - xform/ü/v/
      - xform/(^|')([a-z]+)(?=$|')/${1}${2}<5>/
      - xform/ā([a-z]*)(?=$|')/a${1}<1>/
      - xform/á([a-z]*)(?=$|')/a${1}<2>/
      - xform/ǎ([a-z]*)(?=$|')/a${1}<3>/
      - xform/à([a-z]*)(?=$|')/a${1}<4>/
      - xform/ō([a-z]*)(?=$|')/o${1}<1>/
      - xform/ó([a-z]*)(?=$|')/o${1}<2>/
      - xform/ǒ([a-z]*)(?=$|')/o${1}<3>/
      - xform/ò([a-z]*)(?=$|')/o${1}<4>/
      - xform/ē([a-z]*)(?=$|')/e${1}<1>/
      - xform/é([a-z]*)(?=$|')/e${1}<2>/
      - xform/ě([a-z]*)(?=$|')/e${1}<3>/
      - xform/è([a-z]*)(?=$|')/e${1}<4>/
      - xform/ī([a-z]*)(?=$|')/i${1}<1>/
      - xform/í([a-z]*)(?=$|')/i${1}<2>/
      - xform/ǐ([a-z]*)(?=$|')/i${1}<3>/
      - xform/ì([a-z]*)(?=$|')/i${1}<4>/
      - xform/ū([a-z]*)(?=$|')/u${1}<1>/
      - xform/ú([a-z]*)(?=$|')/u${1}<2>/
      - xform/ǔ([a-z]*)(?=$|')/u${1}<3>/
      - xform/ù([a-z]*)(?=$|')/u${1}<4>/
      - xform/ǖ([a-z]*)(?=$|')/v${1}<1>/
      - xform/ǘ([a-z]*)(?=$|')/v${1}<2>/
      - xform/ǚ([a-z]*)(?=$|')/v${1}<3>/
      - xform/ǜ([a-z]*)(?=$|')/v${1}<4>/
      - xform/ń([a-z]*)(?=$|')/n${1}<2>/
      - xform/ň([a-z]*)(?=$|')/n${1}<3>/
      - xform/ǹ([a-z]*)(?=$|')/n${1}<4>/
      - xform/ḿ([a-z]*)(?=$|')/m${1}<2>/
      - xform/m̀([a-z]*)(?=$|')/m${1}<4>/

      # 万象拼音的 m n 特殊拼音处理
      - xform/(^|')ng(?=$|['<])/${1}eng/
      - xform/(^|')n(?=$|['<])/${1}en/
      - xform/(^|')m(?=$|['<])/${1}me/
    自然码: # 全拼转自然码
      - derive/(^|')([jqxy])u(?=^|$|'|(<[1-5]>))/${1}${2}v/
      - derive/(^|')([aoe])([ioun])(?=^|$|'|(<[1-5]>))/${1}${2}${2}${3}/
      - xform/(^|')([aoe])(ng)?(?=^|$|'|(<[1-5]>))/${1}${2}${2}${3}/
      - xform/iu(?=^|$|'|(<[1-5]>))/<q>/
      - xform/[iu]a(?=^|$|'|(<[1-5]>))/<w>/
      - xform/[uv]an(?=^|$|'|(<[1-5]>))/<r>/
      - xform/[uv]e(?=^|$|'|(<[1-5]>))/<t>/
      - xform/(ing|uai)(?=^|$|'|(<[1-5]>))/<y>/
      - xform/(^|')sh/${1}<u>/
      - xform/(^|')ch/${1}<i>/
      - xform/(^|')zh/${1}<v>/
      - xform/uo(?=^|$|'|(<[1-5]>))/<o>/
      - xform/[uv]n(?=^|$|'|(<[1-5]>))/<p>/
      - xform/([a-z>])i?ong(?=^|$|'|(<[1-5]>))/$1<s>/
      - xform/[iu]ang(?=^|$|'|(<[1-5]>))/<d>/
      - xform/([a-z>])en(?=^|$|'|(<[1-5]>))/$1<f>/
      - xform/([a-z>])eng(?=^|$|'|(<[1-5]>))/$1<g>/
      - xform/([a-z>])ang(?=^|$|'|(<[1-5]>))/$1<h>/
      - xform/ian(?=^|$|'|(<[1-5]>))/<m>/
      - xform/([a-z>])an(?=^|$|'|(<[1-5]>))/$1<j>/
      - xform/iao(?=^|$|'|(<[1-5]>))/<c>/
      - xform/([a-z>])ao(?=^|$|'|(<[1-5]>))/$1<k>/
      - xform/([a-z>])ai(?=^|$|'|(<[1-5]>))/$1<l>/
      - xform/([a-z>])ei(?=^|$|'|(<[1-5]>))/$1<z>/
      - xform/ie(?=^|$|'|(<[1-5]>))/<x>/
      - xform/ui(?=^|$|'|(<[1-5]>))/<v>/
      - xform/([a-z>])ou(?=^|$|'|(<[1-5]>))/$1<b>/
      - xform/in(?=^|$|'|(<[1-5]>))/<n>/

      - xform/<([a-z])>/$1/
    九宫格:
      # |by*|kvc|qso|
      # |fnz|pix|gte|
      # |jml|ruw|hda|
      - xform/b/<11>/
      - xform/y/<12>/
      - xform/k/<21>/
      - xform/v/<22>/
      - xform/c/<23>/
      - xform/q/<31>/
      - xform/s/<32>/
      - xform/o/<33>/
      - xform/f/<41>/
      - xform/n/<42>/
      - xform/z/<43>/
      - xform/p/<51>/
      - xform/i/<52>/
      - xform/x/<53>/
      - xform/g/<61>/
      - xform/t/<62>/
      - xform/e/<63>/
      - xform/j/<71>/
      - xform/m/<72>/
      - xform/l/<73>/
      - xform/r/<81>/
      - xform/u/<82>/
      - xform/w/<83>/
      - xform/h/<91>/
      - xform/d/<92>/
      - xform/a/<93>/

      - xform/<[1-9]1><[1-9]1>/${0}1/
      - xform/<[1-9]1><[1-9]2>/${0}2/
      - xform/<[1-9]1><[1-9]3>/${0}3/
      - xform/<[1-9]2><[1-9]1>/${0}4/
      - xform/<[1-9]2><[1-9]2>/${0}5/
      - xform/<[1-9]2><[1-9]3>/${0}6/
      - xform/<[1-9]3><[1-9]1>/${0}7/
      - xform/<[1-9]3><[1-9]2>/${0}8/
      - xform/<[1-9]3><[1-9]3>/${0}9/
      - xform/<([1-9])[1-3]>/${1}/
    imr_double:
      __include: speller/algebra/声调
      __append:
        __include: speller/algebra/自然码
        __append:
          - derive/^(..)<[1-5]>$/$1/
          - derive/^(.).+(<[1-5]>)$/$1$2/
          - xform/<1>/7/
          - xform/<2>/8/
          - xform/<3>/9/
          - xform/<4>/0/
          - xform/<5>/00/
    imr_T93:
      __include: speller/algebra/声调
      __append:
        __include: speller/algebra/自然码
        __append:
          __include: speller/algebra/九宫格
          __append:
            # 允许 N00
            - derive/^([1-9])[1-9]{2}(?=$|(<[1-5]>))/${1}00/
            # 允许 NN0
            - derive/^([1-9][1-9])[1-9](?=$|(<[1-5]>))/${1}0/
            - derive/^(...)<[1-5]>$/$1/
            # - derive/^(..).+(<[1-5]>)$/$1$2/ # 补零后不存在 不补零需要添加
            # - derive/^(.).+(<[1-5]>)$/$1$2/  # 补零后不存在 不补零需要添加
            - xform/<1>/a/
            - xform/<2>/b/
            - xform/<3>/c/
            - xform/<4>/d/
            - xform/<5>/e/
    imr_PC9:
      __include: speller/algebra/声调
      __append:
        # - abbrev/^([a-z]).+$/$1/ # 超级简拼
        # - abbrev/^([zcs]h).+$/$1/ # 超级简拼中，zh ch sh 视为整体（ch'sh → 城市），而不是像这样分开（c'h's'h → 吃好睡好）。

        - derive/^([a-z]*)<[1-5]>$/$1/
        # ### 小键盘九宫格映射
        # ***  abc def
        # ghi  jkl mno
        # pqrs tuv wxyz

        # derive 允许英文拼音
        - derive/[abc]/8/
        - derive/[def]/9/
        - derive/[hgi]/4/
        - derive/[jkl]/5/
        - derive/[omn]/6/
        - derive/[pqrs]/1/
        - derive/[tuv]/2/
        - derive/[wxyz]/3/
        # 只允许纯数字或纯英文
        - erase/.*[1-9].*[a-z].*/
        - erase/.*[a-z][^<]*[1-9].*/
        # 英文前后加'
        - xform/([a-z]+(<[1-5]>)?)/[${1}]/

        - xform/([1-9]+)<1>/${1}q/
        - xform/([1-9]+)<2>/${1}w/
        - xform/([1-9]+)<3>/${1}e/
        - xform/([1-9]+)<4>/${1}r/
        - xform/([1-9]+)<5>/${1}t/

        - xform/([a-z]+)<([1-5])>/${1}${2}/
    imr_double_pinyin_radical_pinyin:
      __include: speller/algebra/自然码
      __append: # 去掉分隔符
        - xform/'//
    imr_T93_radical_pinyin:
      __include: speller/algebra/自然码
      __append:
        __include: speller/algebra/九宫格
        __append:
          - xform/'//
translator:
  preedit_format:
    自然码:
      # 自然码双拼
      - xform/(^|[ '])aa/${1}a/
      - xform/(^|[ '])ee/${1}e/
      - xform/(^|[ '])oo/${1}o/
      - xform/([bpmnljqxy])n/${1}in/
      - xform/(\w)g/${1}eng/
      - xform/(\w)q/${1}iu/
      - xform/([gkhvuirzcs])w/${1}ua/
      - xform/(\w)w/${1}ia/
      - xform/([dtnlgkhjqxyvuirzcs])r/${1}uan/
      - xform/(\w)t/${1}ve/
      - xform/([gkhvuirzcs])y/${1}uai/
      - xform/(\w)y/${1}ing/
      - xform/([dtnlgkhvuirzcs])o/${1}uo/
      - xform/(\w)p/${1}un/
      - xform/([jqx])s/${1}iong/
      - xform/(\w)s/${1}ong/
      - xform/([jqxnlb])d/${1}iang/
      - xform/(\w)d/${1}uang/
      - xform/(\w)f/${1}en/
      - xform/(\w)h/${1}ang/
      - xform/(\w)j/${1}an/
      - xform/(\w)k/${1}ao/
      - xform/(\w)l/${1}ai/
      - xform/(\w)z/${1}ei/
      - xform/(\w)x/${1}ie/
      - xform/(\w)c/${1}iao/
      - xform/([dtgkhvuirzcs])v/${1}ui/
      - xform/(\w)b/${1}ou/
      - xform/(\w)m/${1}ian/
      - xform/([aoe])\1(\w)/${1}${2}/
      - xform/(^|[ '])v/${1}zh/
      - xform/(^|[ '])i/${1}ch/
      - xform/(^|[ '])u/${1}sh/
      - xform/([jqxy])v/${1}u/
      - xform/([nl])v/${1}ü/
      - xform/(?<=[A-Z])\s(?=[A-Z])// # 消除大写字母之间的空格
    声调:
      - xform/a([a-z]*)<1>/ā${1}/
      - xform/a([a-z]*)<2>/á${1}/
      - xform/a([a-z]*)<3>/ǎ${1}/
      - xform/a([a-z]*)<4>/à${1}/

      - xform/e([a-z]*)<1>/ē${1}/
      - xform/e([a-z]*)<2>/é${1}/
      - xform/e([a-z]*)<3>/ě${1}/
      - xform/e([a-z]*)<4>/è${1}/

      - xform/o([a-z]*)<1>/ō${1}/
      - xform/o([a-z]*)<2>/ó${1}/
      - xform/o([a-z]*)<3>/ǒ${1}/
      - xform/o([a-z]*)<4>/ò${1}/

      - xform/iu<1>/iū/
      - xform/iu<2>/iú/
      - xform/iu<3>/iǔ/
      - xform/iu<4>/iù/

      - xform/i([a-z]*)<1>/ī${1}/
      - xform/i([a-z]*)<2>/í${1}/
      - xform/i([a-z]*)<3>/ǐ${1}/
      - xform/i([a-z]*)<4>/ì${1}/

      - xform/u([a-z]*)<1>/ū${1}/
      - xform/u([a-z]*)<2>/ú${1}/
      - xform/u([a-z]*)<3>/ǔ${1}/
      - xform/u([a-z]*)<4>/ù${1}/

      - xform/ü([a-z]*)<1>/ǖ${1}/
      - xform/ü([a-z]*)<2>/ǘ${1}/
      - xform/ü([a-z]*)<3>/ǚ${1}/
      - xform/ü([a-z]*)<4>/ǜ${1}/

      - xform/<1>/¹/
      - xform/<2>/²/
      - xform/<3>/³/
      - xform/<4>/⁴/
      - xform/<5>/⁰/
    初始化:
      imr_T93:
        - xform/a/<1>/
        - xform/b/<2>/
        - xform/c/<3>/
        - xform/d/<4>/
        - xform/e/<5>/
        # 第三键
        - xform/(^|[ '])([1-9])([1-9])1/${1}<${2}1><${3}1>/
        - xform/(^|[ '])([1-9])([1-9])2/${1}<${2}1><${3}2>/
        - xform/(^|[ '])([1-9])([1-9])3/${1}<${2}1><${3}3>/
        - xform/(^|[ '])([1-9])([1-9])4/${1}<${2}2><${3}1>/
        - xform/(^|[ '])([1-9])([1-9])5/${1}<${2}2><${3}2>/
        - xform/(^|[ '])([1-9])([1-9])6/${1}<${2}2><${3}3>/
        - xform/(^|[ '])([1-9])([1-9])7/${1}<${2}3><${3}1>/
        - xform/(^|[ '])([1-9])([1-9])8/${1}<${2}3><${3}2>/
        - xform/(^|[ '])([1-9])([1-9])9/${1}<${2}3><${3}3>/
        # 九宫格数字映射
        # |by*|kvc|qso|
        # |fnz|pix|gte|
        # |jml|ruw|hda|
        - xform/<11>/b/
        - xform/<12>/y/
        - xform/<21>/k/
        - xform/<22>/v/
        - xform/<23>/c/
        - xform/<31>/q/
        - xform/<32>/s/
        - xform/<33>/o/
        - xform/<41>/f/
        - xform/<42>/n/
        - xform/<43>/z/
        - xform/<51>/p/
        - xform/<52>/i/
        - xform/<53>/x/
        - xform/<61>/g/
        - xform/<62>/t/
        - xform/<63>/e/
        - xform/<71>/j/
        - xform/<72>/m/
        - xform/<73>/l/
        - xform/<81>/r/
        - xform/<82>/u/
        - xform/<83>/w/
        - xform/<91>/h/
        - xform/<92>/d/
        - xform/<93>/a/
      imr_PC9:
        - xform/\[([a-z]+)([1-5])\]/[${1}<${2}>]/
      imr_double_pinyin_radical_lookup:
        - xform/([a-z]{2})(?=[^'])/${1}'/
      imr_T93_radical_lookup:
        - xform/([1-9]{3})(?=[^'])/${1}'/
    imr_T93:
      __include: translator/preedit_format/初始化/imr_T93
      __append:
        __include: translator/preedit_format/自然码
        __append:
          __include: translator/preedit_format/声调
    imr_PC9:
      __include: translator/preedit_format/初始化/imr_PC9
      __append:
        __include: translator/preedit_format/声调
        __append:
          - xlit/[]7/【】'/
          - xform/([1-9])q/${1}¹/
          - xform/([1-9])w/${1}²/
          - xform/([1-9])e/${1}³/
          - xform/([1-9])r/${1}⁴/
          - xform/([1-9])t/${1}⁰/
    imr_double_pinyin_radical_lookup:
      __include: translator/preedit_format/初始化/imr_double_pinyin_radical_lookup
      __append:
        __include: translator/preedit_format/自然码
    imr_T93_radical_lookup:
      __include: translator/preedit_format/初始化/imr_T93_radical_lookup
      __append:
        __include: translator/preedit_format/imr_T93
    imr_T93_stroke_lookup:
      - xlit/12345/⼀⼁⼃⼂⼄/
    imr_PC9_stroke:
      - xlit/62135/⼀⼁⼃⼂⼄/

  comment_format:
    万象:
      - xform/^ng(?= |$)/eng/
      - xform/ ng(?= |$)/ eng/
      - xform/ńg/éng/
      - xform/ňg/ěng/
      - xform/ǹg/èng/
      - xform/^n(?= |$)/en/
      - xform/ n(?= |$)/ en/
      - xform/ń/én/
      - xform/ň/ěn/
      - xform/ǹ/èn/
      - xform/^m(?= |$)/me/
      - xform/ m(?= |$)/ me/
      - xform/ḿ/mé/
      - xform/m̀/mè/
